"""add_salary_range_excitement_and_date_fields_to_application

Revision ID: 528ea0bbfe26
Revises: d9f4a2c7e1b3
Create Date: 2026-08-28 16:52:00.045921

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '528ea0bbfe26'
down_revision: Union[str, Sequence[str], None] = 'd9f4a2c7e1b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('application', schema=None) as batch_op:
        batch_op.add_column(sa.Column('min_salary', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('max_salary', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('excitement', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('date_posted', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('deadline', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('follow_up', sa.Date(), nullable=True))
        batch_op.drop_column('salary')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('application', schema=None) as batch_op:
        batch_op.add_column(sa.Column('salary', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('follow_up')
        batch_op.drop_column('deadline')
        batch_op.drop_column('date_posted')
        batch_op.drop_column('excitement')
        batch_op.drop_column('max_salary')
        batch_op.drop_column('min_salary')

    # ### end Alembic commands ###
